### ISSUE TITLE
Leaving behind file: /etc/apt/apt.conf.d/20auto-upgrades.ucf-dist ?

### ISSUE THREAD

**Issue by msabramo** [jnv/ansible-role-unattended-upgrades#10]
After using this role on a couple of machines, it set up unattended upgrades (yay!), but it seems that it might be leaving behind a file `/etc/apt/apt.conf.d/20auto-upgrades.ucf-dist`?

```
CORP\marca@marcatest1:~$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
```

I'll try to take a look and see if I can figure out what's going on.

**Comment by msabramo** [comment]
Hmmm, I don't see the Ansible code doing this so probably when the apt package is installed, this file gets dropped. So maybe we should add something like:

```yaml
- name: remove 20auto-upgrades.ucf-dist if present
  file: path=/etc/apt/apt.conf.d/20auto-upgrades.ucf-dist state=absent
```

?

**Comment by msabramo** [comment]
Hmmm, maybe it's not coming at all from this role and it's coming from me manually installing stuff and then when I get prompted what to do about the config files?

http://manpages.ubuntu.com/manpages/trusty/man1/ucf.1.html

**Comment by jnv** [comment]
Hey Marc, thanks for report! I'm not sure either, but it is likely that you ran into conflict with configuration files, though I'm not sure how could that happen. The role installs the package first and then it writes `20auto-upgrades` file. Did you install unattended-upgrades manually or with other role? Also, could you please show me the diff between `20auto-upgrades` and `20auto-upgrades.ucf-dist`?

**Comment by jnv** [comment]
Sorry but I can't help you with this issue without further information. Please tell me if you learn more, I will close this in meantime.

**Comment by Eslam-Bouz** [comment]
Hey ... i Have The same Err .. :( Bad Luck !

What i did is `sudo rm /etc/apt/apt.conf.d/20auto-upgrades.ucf-d `

and The Err is Died :+1:
