### ISSUE TITLE
Ansible playbook 

### ISSUE THREAD

**Issue by adi2909** [jnv/ansible-role-unattended-upgrades#23]
Hi,

Thank you for sharing this module. I have a couple of questions based on my current setup. I am using packer to build a virtualbox-ovf. Within my scripts and modules I am using Ansible to install a bunch of packages + the unattended ones. 

The roles folder structure is identical to yours. While running the playbook all the tasks succeed as well however when i log on to the virtualbox vm to check if unattended was installed and /etc/apt/apt.conf.d/50unattened was modified..... I dont see any changes. 

Any opinion on what could be causing this ? My main.yml calling the role looks like: 

```yaml
- hosts: all
  roles:
    - { role: qcs.users, sudo: yes }
    - qcs.base-pkgs
    - role: unattended
```

Output of my playbook when I run packer build: 

    virtualbox-ovf: TASK [unattended : include] ****************************************************
    virtualbox-ovf: included: /tmp/packer-provisioner-ansible-local/roles/unattended/tasks/unattended-upgrades.yml for 127.0.0.1
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : add distribution-specific variables] ************************
    virtualbox-ovf: ok: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : install unattended-upgrades] ********************************
    virtualbox-ovf: ok: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : install reboot dependencies] ********************************
    virtualbox-ovf: skipping: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : create APT auto-upgrades configuration] *********************
    virtualbox-ovf: changed: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : create unattended-upgrades configuration] *******************
    virtualbox-ovf: changed: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: PLAY RECAP *********************************************************************
    virtualbox-ovf: 127.0.0.1                  : ok=19   changed=14   unreachable=0    failed=0

**Comment by jnv** [comment]
Hi Adi, could you please show me the resulting 50unattended file? Also, do you set any variables for the unattended-upgrades role, or do you just go with defaults? You could also check for `/etc/apt/apt.conf.d/20auto-upgrades` file, whether it is identical to `files/auto-upgrades`.

Two options come into my mind: either packer does not provision correctly the resulting image (which seems unlikely), or the changed configuration file gets overriden… somehow. This role just uses Ansible's `template` command to create the configuration file, so I assume the provision should fail in case the fail couldn't be changed.

**Comment by adi2909** [comment]
I left the default file as is for the test run. 

Aut-upgrades file has: 

APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";

Unattended.yml under tasks: 

---
- name: add distribution-specific variables
  sudo: yes
  include_vars: "{{ ansible_distribution }}.yml"

- name: install unattended-upgrades
  sudo: yes
  apt: pkg=unattended-upgrades state=present

- name: install reboot dependencies
  sudo: yes
  include: reboot.yml
  when: unattended_automatic_reboot

- name: create APT auto-upgrades configuration
  sudo: yes
  copy: >
    src=auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644

- name: create unattended-upgrades configuration
  sudo: yes
  template: >
    src=unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644

When i SSH onto the box and navigate to the /etc/apt/apt.d.conf folder: 

root@vagrant-ubuntu-wily-64:/etc/apt/apt.conf.d# ll
total 52
drwxr-xr-x 2 root root 4096 Mar 29 21:41 ./
drwxr-xr-x 6 root root 4096 Apr 20 03:51 ../
-rw-r--r-- 1 root root  643 Oct  5  2015 01autoremove
-rw-r--r-- 1 root root 1047 Mar 29 21:40 01autoremove-kernels
-rw-r--r-- 1 root root  123 Oct  5  2015 01-vendor-ubuntu
-rw-r--r-- 1 root root  129 Sep 17  2015 10periodic
-rw-r--r-- 1 root root  108 Sep 17  2015 15update-stamp
-rw-r--r-- 1 root root   85 Sep 17  2015 20archive
-rw-r--r-- 1 root root  123 Oct  5  2015 20changelog
-rw-r--r-- 1 root root 2331 Jan 21 22:07 50unattended-upgrades
-rw-r--r-- 1 root root  182 Aug 12  2015 70debconf
-rw-r--r-- 1 root root   80 Apr 20 03:50 90cloud-init-pipelining
-rw-r--r-- 1 root root  231 Sep 17  2015 99update-notifier


More on 50unattended-upgrades: 

Unattended-Upgrade::Allowed-Origins {
	"${distro_id}:${distro_codename}-security";
//	"${distro_id}:${distro_codename}-updates";
//	"${distro_id}:${distro_codename}-proposed";
//	"${distro_id}:${distro_codename}-backports";
};

// List of packages to not update (regexp are supported)
Unattended-Upgrade::Package-Blacklist {
//	"vim";
//	"libc6";
//	"libc6-dev";
//	"libc6-i686";
};

// This option allows you to control if on a unclean dpkg exit
// unattended-upgrades will automatically run 
//   dpkg --force-confold --configure -a
// The default is true, to ensure updates keep getting installed
//Unattended-Upgrade::AutoFixInterruptedDpkg "false";

// Split the upgrade into the smallest possible chunks so that
// they can be interrupted with SIGUSR1. This makes the upgrade
// a bit slower but it has the benefit that shutdown while a upgrade
// is running is possible (with a small delay)
//Unattended-Upgrade::MinimalSteps "true";

// Install all unattended-upgrades when the machine is shuting down
// instead of doing it in the background while the machine is running
// This will (obviously) make shutdown slower
//Unattended-Upgrade::InstallOnShutdown "true";


the fact that 50unattended-upgrades was last changed on Jan 21st leads me to believe that the file is not being written or modified. 


Also surprisingly enough I do see a file called 20auto-upgrades. 


Here is output from my last run: 

    virtualbox-ovf: deprecation_warnings=False in ansible.cfg.
    virtualbox-ovf: included: /tmp/packer-provisioner-ansible-local/roles/unattended/tasks/unattended-upgrades.yml for 127.0.0.1
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : add distribution-specific variables] ************************
    virtualbox-ovf: ok: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : install unattended-upgrades] ********************************
    virtualbox-ovf: ok: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : install reboot dependencies] ********************************
    virtualbox-ovf: skipping: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : create APT auto-upgrades configuration] *********************
    virtualbox-ovf: changed: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: TASK [unattended : create unattended-upgrades configuration] *******************
    virtualbox-ovf: changed: [127.0.0.1]
    virtualbox-ovf:
    virtualbox-ovf: PLAY RECAP *********************************************************************
    virtualbox-ovf: 127.0.0.1                  : ok=6    changed=2    unreachable=0    failed=0

**Comment by jnv** [comment]
Huh, I don't see the file `20auto-upgrades` in your file listing, just `10periodic` which was used in older versions. So it looks like Packer does not perform file operations with correct files. Perhaps you should bump up Ansible's verbosity so you see what's exactly going on.

**Comment by adi2909** [comment]
So it turns out that packer was giving me a hard time while building my image. I fixed that and re-built an image. 

Now the /etc/apt/apt.d.conf looks like: 

drwxr-xr-x 2 root root 4096 Apr 21 16:42 ./
drwxr-xr-x 6 root root 4096 Apr 20 03:51 ../
-rw-r--r-- 1 root root  643 Oct  5  2015 01autoremove
-rw-r--r-- 1 root root 1047 Mar 29 21:40 01autoremove-kernels
-rw-r--r-- 1 root root  123 Oct  5  2015 01-vendor-ubuntu
-rw-r--r-- 1 root root  129 Sep 17  2015 10periodic
-rw-r--r-- 1 root root  108 Sep 17  2015 15update-stamp
-rw-r--r-- 1 root root   85 Sep 17  2015 20archive
-rw-r--r-- 1 root root  168 Apr 21 14:05 20auto-upgrades
-rw-r--r-- 1 root root  123 Oct  5  2015 20changelog
-rw-r--r-- 1 root root  426 Apr 21 16:42 50unattended-upgrades
-rw-r--r-- 1 root root  182 Aug 12  2015 70debconf
-rw-r--r-- 1 root root   80 Apr 20 03:50 90cloud-init-pipelining
-rw-r--r-- 1 root root  231 Sep 17  2015 99update-notifier

Output of the 50 unattended file: 

 more 50unattended-upgrades 
// Unattended-Upgrade::Origins-Pattern controls which packages are
// upgraded.
Unattended-Upgrade::Origins-Pattern {
     "origin=Ubuntu,archive=${distro_codename}-security,label=Ubuntu";
  };

// List of packages to not update (regexp are supported)
Unattended-Upgrade::Package-Blacklist {
};

// Use apt bandwidth limit feature, this example limits the download
// speed to 70kb/sec
//Acquire::http::Dl-Limit "70";

Output of 20auto-upgrades: 

# more 20auto-upgrades 
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";


Sorry I have been bugging you with this but 2 follow up questions: 

1) How do I verify that unattened-upgrades installed correctly / running ?
2) Generally when a package is installed i check the dpkg logs to confirm... I checked the logs and I dont see unattended installed. And under logs I only see: 

/var/log/unattended-upgrades# ll
total 8
drwxr-x---  2 root adm    4096 Apr 20 03:50 ./
drwxrwxr-x 10 root syslog 4096 Apr 21 15:16 ../
-rw-r--r--  1 root root      0 Apr 20 03:50 unattended-upgrades-shutdown.log


Any suggestions?

**Comment by jnv** [comment]
Glad to know you have found the solution!

> 1) How do I verify that unattened-upgrades installed correctly / running ?

Running `sudo unattended-upgrades --dry-run -d` should help you to verify your setup.

> 2) Generally when a package is installed i check the dpkg logs to confirm... I checked the logs and I dont see unattended installed.

Perhaps packer cleans-up the logs before finishing the build? No idea.
Anyway `unattended-upgrades` command above will be available iff the package has been installed. You should also check for `/etc/cron.daily/apt` script, which runs unattended-upgrades on a daily basis.

Hopefully this answers your questions, I will close this issue now.
