### ISSUE TITLE
Ubuntu 16.04 - using systemctl-timer instead of relying on cron.daily

### ISSUE THREAD

**Issue by FJerusalem** [jnv/ansible-role-unattended-upgrades#26]
systemctl list-timers
-Will cause trouble if you want to upgrade at a fixed time; planning backups prior upgrade for example.

No solution found yet.
Reference:
http://askubuntu.com/questions/824718/ubuntu-16-04-unattended-upgrades-runs-at-random-times

**Comment by jnv** [comment]
Thanks for your suggestion, but purpose of this role is not to implement workarounds which should be fixed elsewhere. AFAIK this seems to be a problem concerning Unattended Upgrades package itself or systemd respectively.
