### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by hoall** [jnv/ansible-role-unattended-upgrades#27]
Hey,

your build is failing. I expect that it'll work anyway, but reduce your travis output to go on 'passing' again.

Thanks a lot for your work.

Best regards,
Felix

**Comment by jnv** [comment]
Thanks for noticing. Either `unattended-upgrades` is stuck in loop or there is something funny going on with Travis' sources.list.

I guess the CI tests should be rewritten since the state of the art moved ahead. For example [molecule](https://github.com/metacloud/molecule) looks nice.
