### ISSUE TITLE
Debian Stretch Support

### ISSUE THREAD

**Issue by mcordingley** [jnv/ansible-role-unattended-upgrades#34]
Stretch enters hard freeze February 5th, per the [release timeline.](https://wiki.debian.org/DebianStretch) Would be nice if this role supported Stretch before the final release so we can test against it and have it ready to go on release day.

Thanks!

**Comment by jnv** [comment]
Sure, are there any changes in the dependent packages which need to be considered?

**Comment by mcordingley** [comment]
Actually, I had some time with this last night, and I think it's good. The failing dependency (update-notifier) threw me into thinking that it wasn't 100%, but after reading up on #6 I see what's going on and that it's all good.

Thanks!

**Comment by varac** [comment]
Please update the `main.yml` file to indicate that this role supports Debian stretch.
