### ISSUE TITLE
Add bandwidth limit variable?

### ISSUE THREAD

**Issue by BarbzYHOOL** [jnv/ansible-role-unattended-upgrades#50]
//Acquire::http::Dl-Limit "70";

I would like to set the bandwith limit, but it's the only missing variable in that role. Is it possible to add it?

**Comment by jnv** [comment]
@BarbzYHOOL Sure, would you like to make a PR for it?

**Comment by BarbzYHOOL** [comment]
I don't master the template stuff with jinja yet, hence why I asked, sorry (already overwhelmed with all this new ansible thing)
