### ISSUE TITLE
[Feature Request] Use force_apt_get

### ISSUE THREAD

**Issue by lonix1** [jnv/ansible-role-unattended-upgrades#64]
I get this on ubuntu 18:

> [WARNING]: Could not find aptitude. Using apt-get instead

Please use `force_apt_get: yes` to avoid this.

**Comment by jnv** [comment]
Thanks for suggestion! I suppose this shouldn't cause any compatibility issues. However, since this is Ansible 2.4+ feature, I'd prefer to put this into next major version with other breaking changes.

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.
