### ISSUE TITLE
APT::Periodic::Enable not set

### ISSUE THREAD

**Issue by mtdcr** [jnv/ansible-role-unattended-upgrades#78]
It would be nice, if `APT::Periodic::Enable` could be set explicitly by this role. [Armbian](https://www.armbian.com/), for example, installs 
`/etc/apt/apt.conf.d/02-armbian-periodic`, which contains `APT::Periodic::Enable "0";`.

**Comment by jnv** [comment]
Yeah, I have received previous reports that some VPN providers also disable APT Periodic in their default setups. I guess it would be a nice addition to #66.

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.
