### ISSUE TITLE
New versions missing on ansible galaxy

### ISSUE THREAD

**Issue by Perflyst** [jnv/ansible-role-unattended-upgrades#89]
The latest version on galaxy is v1.11.0. The newer version are missing.

**Comment by Normo** [comment]
:information_source: The missing versions are now available on Ansible Galaxy. This can be closed.

**Comment by jnv** [comment]
Yeah, I have manually triggered the import. Unfortunately Galaxy supports only Travis webhooks and Travis has been deprecated. I would like to keep this issue open as a reminder this needs to be handled with switching to GitHub Actions. 😩

**Comment by misilot** [comment]
@jnv 

this Github Action should do the trick https://github.com/geerlingguy/ansible-role-mysql/blob/master/.github/workflows/release.yml

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.
