### ISSUE TITLE
[Feature Request] role variables: unattended_dev_release, unattended_remove_unused_kernel_packages

### ISSUE THREAD

**Issue by dionysius** [jnv/ansible-role-unattended-upgrades#91]
While merging my current config with what this role provides, there seem to be no options for:

1) unattended_dev_release
> // This option controls whether the development release of Ubuntu will be
> // upgraded automatically. Valid values are "true", "false", and "auto".
> Unattended-Upgrade::DevRelease "auto";

2) unattended_remove_unused_kernel_packages
> // Remove unused automatically installed kernel-related packages
> // (kernel images, kernel headers and kernel version locked tools).
> Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.
