### ISSUE TITLE
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead

### ISSUE THREAD

**Issue by haydenseitz** [jnv/ansible-role-unattended-upgrades#95]
From playbook output:

```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

https://github.com/jnv/ansible-role-unattended-upgrades/blob/38d05afe93c2dcc719c612474f7afaab0d6fb8f3/tasks/main.yml#L1
https://github.com/jnv/ansible-role-unattended-upgrades/blob/7ed7c8c711ee19e44644b26a7785181650e17683/tasks/unattended-upgrades.yml#L29

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.
