### ISSUE TITLE
Ability to Specify Patch Install Time with Systemd

### ISSUE THREAD

**Issue by misilot** [jnv/ansible-role-unattended-upgrades#97]
Source: https://wiki.debian.org/UnattendedUpgrades

Add the ability to override for upgrades.

Should create the path/file `/etc/systemd/system/apt-daily-upgrade.timer.d/override.conf` with the following

```
[Timer]
OnCalendar=
OnCalendar=01:00  -- Should be a customizable variable
RandomizedDelaySec=0 -- should be a customizable variable
```

Defaults (ubuntu 18.04 at least)
```
[Timer]
OnCalendar=*-*-* 6:00
RandomizedDelaySec=60m
```

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.

**Comment by Paul-Weisser** [comment]
@misilot Do u seek a solution for this? I am thinking about maintaining a fork of this Repo and this would be feature thats definitely on my list of important features to add.
