### ISSUE TITLE
THIS ROLE IS DEPRECATED: Rationale & Alternatives

### ISSUE THREAD

**Issue by jnv** [jnv/ansible-role-unattended-upgrades#98]
Unfortunately I don't have time nor motivation to maintain this role anymore, so with this I announce that the **`jnv.unattended-upgrades` role is deprecated**.

This probably doesn't come as a surprise with multiple unanswered issues and pull requests. I originally hoped to finish the migration to v2.0 of this role with #32, but with the [closure of Travis CI](https://blog.travis-ci.com/2021-05-07-orgshutdown) I have lost the testing setup. And since I don't use this role myself anymore (nor Ansible), I don't have any confidence in pushing changes to this role.

I appreciate all the time you spent with your contributions and I am sorry if your PR wasn't accepted.

## What's next?

I have pushed one last update with link to this issue in the README and marked the role as deprecated in Galaxy.

I won't be accepting pull requests and bug reports, but I won't archive the repository to keep this issue open for comments.

I would like to collect alternatives and significant forks of this role in this issue. Please, comment with your recommendations – especially for roles with a migration path from this role!

## Unresolved issues and pull requests

The following issues remain unresolved with this role:

- #32 and #66 
- #46 
- #47 and #85 
- #53 and #59
- #57 
- #63 
- #64 
- #68 
- #78 
- #82 
- #89 
- #91 
- #94 and #92 
- #97 
- #40 
- #58 
- #83 
- #84 

## Alternative roles

Check out the maintained fork of this role by @hifis-net: https://github.com/hifis-net/ansible-role-unattended-upgrades ([`hifis.unattended_upgrades`](https://galaxy.ansible.com/hifis/unattended_upgrades) on Galaxy).

Other roles with similar purpose (I haven't tested them, but they seem actively maintained and popular):

- https://galaxy.ansible.com/weareinteractive/apt
- https://galaxy.ansible.com/geerlingguy/security

Further recommendations are welcome, especially if they provide a migration path from this role.

**Comment by lonix1** [comment]
Thanks for maintaining it up to now.

If you don't use Ansible any longer, what do you use?

**Comment by jnv** [comment]
> If you don't use Ansible any longer, what do you use?

I didn't move to greener pastures, I just don't manage servers anymore. 🙂

**Comment by lonix1** [comment]
That sounds to me like moving to greener pastures! :wink:

**Comment by Normo** [comment]
Thank you very much @jnv!

As a [HIFIS Software](https://github.com/hifis-net) team member I'm happy to tell you that we already created a [**fork**](https://github.com/hifis-net/ansible-role-unattended-upgrades) for this project. As we are actively using the role in our projects, we will continue the development and maintenance of this role. It is available in the [**Ansible Galaxy**](https://galaxy.ansible.com/hifis/unattended_upgrades) and can be installed via this command:
```
$ ansible-galaxy install hifis.unattended_upgrades
```
Feel free to open [issues](https://github.com/hifis-net/ansible-role-unattended-upgrades/issues) or [pull requests](https://github.com/hifis-net/ansible-role-unattended-upgrades/pulls)!

**Comment by jnv** [comment]
Thanks @Normo, that's great news! I have added it to the first post and linked it from the readme.

**Comment by jnv** [comment]
Since we have an official replacement now, I think it's time to archive this repo. So long, and thanks for all the fish!
